# Generated by Django 3.2.7 on 2021-09-24 07:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exoplanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('WJ', 'Warm Jupiter'), ('WN', 'Warm Neptune'), ('WSE', 'Warm Super-Earth'), ('WMN', 'Warm Mini-Neptune'), ('HJ', 'Hot Jupiter'), ('HN', 'Hot Neptune'), ('HSE', 'Hot Super-Earth'), ('HMN', 'Hot Mini-Neptune'), ('CJ', 'Cold Jupiter'), ('CN', 'Cold Neptune'), ('CSE', 'Cold Super-Earth'), ('CMN', 'Cold Mini-Neptune'), ('U', 'Unassigned')], default='U', max_length=3)),
                ('priority', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('total_observations', models.PositiveSmallIntegerField(default=0, null=True)),
                ('recent_observations', models.PositiveSmallIntegerField(default=0, null=True)),
                ('ra_j2000', models.CharField(blank=True, max_length=255, null=True)),
                ('dec_j2000', models.CharField(blank=True, max_length=255, null=True)),
                ('v_mag', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('r_mag', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('gaia_g_mag', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('depth_mmag', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('transit_duration_hours', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('ephemeris_mid_time_bjd_tdb', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('ephemeris_mid_time_uncertainty', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('ephemeris_period_days', models.DecimalField(blank=True, decimal_places=9, max_digits=13, null=True)),
                ('ephemeris_period_uncertainty', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('ephemeris_current_oc_min', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Synthetic_spectre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infoplanets.exoplanet')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ra', models.CharField(max_length=255)),
                ('dec', models.CharField(max_length=255)),
                ('stellar_distance', models.DecimalField(blank=True, decimal_places=9, max_digits=13, null=True)),
                ('parallax', models.DecimalField(blank=True, decimal_places=9, max_digits=13, null=True)),
                ('orbiting_planets', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infoplanets.exoplanet')),
            ],
        ),
        migrations.CreateModel(
            name='Light_curve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infoplanets.exoplanet')),
            ],
        ),
    ]
