# Generated by Django 3.2.7 on 2021-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoplanets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='light_curve',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='star',
            name='ecliptic_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='ecliptic_longiude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='galactic_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='galactic_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mB',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mB_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mGAIA',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mGAIA_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mH',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mH_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mJ',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mJ_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mKS',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mKS_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mTESS',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mTESS_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mV',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mV_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mW1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mW1_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mW2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mW2_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mW3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mW3_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mW4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mW4_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='parallax_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='proper_motion_dec',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='proper_motion_dec_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='proper_motion_ra',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='proper_motion_ra_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='total_proper_motion',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='total_proper_motion_moe',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='synthetic_spectre',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
