# Generated by Django 3.2.7 on 2021-10-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoplanets', '0003_auto_20210928_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='light_curve',
            name='name',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='synthetic_spectre',
            name='name',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
