# Generated by Django 3.2.7 on 2021-10-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoplanets', '0004_auto_20211008_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exoplanet',
            name='priority',
            field=models.CharField(max_length=8),
        ),
    ]
