# Generated by Django 3.2.7 on 2021-10-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoplanets', '0005_alter_exoplanet_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exoplanet',
            name='depth_mmag',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='gaia_g_mag',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='r_mag',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='v_mag',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
