# Generated by Django 3.2.7 on 2021-10-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoplanets', '0006_auto_20211011_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exoplanet',
            name='ephemeris_period_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
